[package]
name = "speeko"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "speeko"
path = "src/main.rs"

[dependencies]
speeko-common = { path = "../common" }
speeko-audio = { path = "../audio" }
speeko-dsp = { path = "../dsp" }
speeko-vad = { path = "../vad" }
speeko-features = { path = "../features" }
speeko-recognizer = { path = "../recognizer" }
speeko-store = { path = "../store" }
clap = { version = "~4.5", features = ["derive"] }
anyhow = "~1.0"
log = "~0.4"
env_logger = "~0.11"
ctrlc = "~3.4"

[[bench]]
name = "inference_bench"
harness = false
